baseURL = 'https://blog.dimlab.fr/'
DefaultContentLanguage = "fr"
title = "Tour des minous"
theme = "beautifulhugo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[Params]
  homeTitle = "" # Set a different text for the header on the home page
  # subtitle = "Un soustitre"
  mainSections = ["post"]
  hideAuthor = true
  logo = "img/logo-black.svg" # Expecting square dimensions
  env = "production"
  # favicon = "img/favicon.ico"

[[Params.bigimg]]
 src = "img/home_back.jpg"

# Social Part
[Author]
  instagram = "dimitripuyet"  
  youtube = "dimitripuyet" # or channel/channelname
  strava = "90502197"

# Menu Part
[[menu.main]]
  name = 'Posts'
  pageRef = '/post'
  weight = 1
[[menu.main]]
  name = 'A Propos'
  pageRef = '/about/index'
  weight = 100
[[menu.main]]
  name = 'Préparatifs'
  pageRef = '/preparatifs'
  weight = 50
[[menu.main]]
  name = 'Santé'
  pageRef = '/preparatifs/sante'
  parent = 'Préparatifs'
  weight = 50

