baseURL = 'https://blog.dimlab.fr/'
DefaultContentLanguage = "fr"
title = "Tour des minous"
theme = "beautifulhugo"
googleAnalytics = "G-DX3YX9CX83"
enableRobotsTXT = true
disqusShortname = "blog-dimlab-fr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[Params]
  homeTitle = "Tour des minous" # Set a different text for the header on the home page
  subtitle = "Suivez nous"
  mainSections = ["post"]
  hideAuthor = true
  logo = "img/logo-black.svg" # Expecting square dimensions
  env = "production"
  comments = true
  socialShare = false
  # favicon = "img/favicon.ico"

[[Params.bigimg]]
 src = "img/home_back.jpg"

# Social Part
[Author]
  instagram = "dimitripuyet"  
  youtube = "dimitripuyet" # or channel/channelname
  strava = "90502197"

# Menu Part
# [[menu.main]]
#   name = 'Posts'
#   pageRef = '/post'
#   weight = 1
[[menu.main]]
  name = 'A Propos'
  pageRef = '/about/index'
  weight = 100
[[menu.main]]
  name = 'Préparatifs'
  pageRef = '/preparatifs'
  weight = 50
[[menu.main]]
  name = 'Destinations'
  weight = 20
  [[menu.main]]
  name = 'Guadeloupe'
pageRef = '/tags/guadeloupe'
  parent = 'Destinations'
  weight = 50